#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set +x

APPNAME="$(hostname)/ssl"

echo "[$APPNAME][$(date)] Started as an s6 service"

# Now wait until NGINX is up
echo "[$APPNAME][$(date)] Waiting for NGINX to come online..."
until [[ -f /tmp/nginx.up ]]
do
    sleep 1
done
echo "[$APPNAME][$(date)] NGINX is online."

# If SSL is not ENABLED, stop forevah
if [[ "${SSL^^}" != "ENABLED" ]]
then
    echo "[$APPNAME][$(date)] SSL disabled"
    cp -f /etc/nginx/sites-available/default.org /etc/nginx/sites-available/default
    killall /usr/sbin/nginx # this will tell s6 to restart the web server process
    sleep infinity
fi


# First let's check if there's a backup. This backup contains the latest, so let's make sure it's installed
if [[ -f /run/nginx/.letsencrypt/letsencrypt.tgz ]]
then
    # if /etc/letsencrypt does not exist, but there is a backup, restore it
    tar xvpfz --overwrite letsencrypt.tgz -C /
elif [[ -d /etc/letsencrypt ]]
then
    # let's make sure it's backed up before we do anything else
    mkdir -p /run/nginx/.letsencrypt
    chmod u=rwx,go= /run/nginx/.letsencrypt
    tar --create --gzip --file=/run/nginx/.letsencrypt/letsencrypt.tgz /etc/letsencrypt /var/lib/letsencrypt /etc/nginx/sites-available/default
    chmod u=rx,go= /run/nginx/.letsencrypt
fi

# Do some checks to ensure that there is enough info to request domains:
if (( ${#SSL_DOMAIN[@]} == 0 ))
then
    # No domains in environment files. Complain and stop trying to install certificates:
    echo "--------------------------------------------------"
    echo "|      STOP ! NGINX SSL configuration problem    |"
    echo "| You must define at least 1 SSL_DOMAIN in your  |"
    echo "| docker-compose.yml file. Go check and fix it!  |"
    echo "| The container will continue without SSL.       |"
    echo "--------------------------------------------------"
    sleep infinity
fi

if ! grep -E "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b" <<< "$SSL_EMAIL" >/dev/null
then
    # No domains in environment files. Complain and stop trying to install certificates:
    echo "--------------------------------------------------------"
    echo "|      STOP ! NGINX SSL configuration problem          |"
    echo "| You must provide a valid email in SSL_EMAIL in your  |"
    echo "| docker-compose.yml file. Go check and fix it!        |"
    echo "| The container will continue without SSL.             |"
    echo "--------------------------------------------------------"
    sleep infinity
fi

if [[ "${SSL_TOS,,}" != "accept" ]]
then
    # No domains in environment files. Complain and stop trying to install certificates:
    echo "--------------------------------------------------------------------------"
    echo "|      STOP ! NGINX SSL configuration problem                            |"
    echo "| You must accept the ACME Account TOS found at                          |"
    echo "| https://letsencrypt.org/repository/#let-s-encrypt-subscriber-agreement |"
    echo "| and set SSL_TOS=ACCEPT in your docker-compose.yml file.                |"
    echo "| Go check and fix it! The container will continue without SSL.          |"
    echo "--------------------------------------------------------------------------"
    sleep infinity
else
    agree_tos="--agree-tos"
fi

# Load up ${newdomains[@]} with any domain names there's not yet a certificate for
newdomains=()
domains=($(/usr/bin/certbot certificates 2>/dev/null | awk '/Domains:/ { $1=""; print substr($0,2) }'))

IFS="," read -ra SSL_DOMAINS <<< "$(echo $SSL_DOMAIN|tr -d '[:blank:]')"
for (( i=0; i<${#SSL_DOMAINS[@]}; i++ ))
do
    [[ ! " ${domains[@]} " =~ " ${SSL_DOMAINS[i]} " ]] && newdomains+=(${SSL_DOMAINS[i]})
done

# Figure out if we want to redirect all queries to SSL?
[[ "${SSL_REDIRECT,,}" == "enabled" ]] && redirect="--redirect" || redirect=""

# prepend "-d " before each domain name:
newdomains=( "${newdomains[@]/#/-d }" )

# Now get new certs for these newdomains:
if (( ${#newdomains[@]} > 0 )) && ! /usr/bin/certbot --quiet --nginx "$agree_tos" "$redirect" -m $SSL_EMAIL ${newdomains[@]}
then
    # Something went wrong
    echo Error in:
    echo "/usr/bin/certbot --quiet --nginx $agree_tos $redirect -m $SSL_EMAIL ${newdomains[@]}"
    echo "--------------------------------------------------"
    echo "| STOP ! NGINX CertBot SSL installation problem  |"
    echo "| Please see the message above.                  |"
    echo "|                                                |"
    echo "| The container will continue without SSL.       |"
    echo "--------------------------------------------------"
    sleep infinity
else
    echo "[$APPNAME][$(date)] SSL Certificates installed for these domains:"
    /usr/bin/certbot certificates
    [[ "${SSL_REDIRECT,,}" == "enabled" ]] && echo "[$APPNAME][$(date)] All web traffic will be redirected to SSL."
    # back things up again:
    mkdir -p /run/nginx/.letsencrypt
    chmod u=rwx,go= /run/nginx/.letsencrypt
    tar --create --gzip --file=/run/nginx/.letsencrypt/letsencrypt.tgz /etc/letsencrypt /var/lib/letsencrypt /etc/nginx/sites-available/default
    chmod u=rx,go= /run/nginx/.letsencrypt
    echo "[$APPNAME][$(date)] nginx will restart now to ensure SSL is enabled"
    killall /usr/sbin/nginx # restart nginx with the SSL stuff installed
    while :
    do
        sleep 1d
        echo "[$APPNAME][$(date)] Checking if SSL certs need renewing..."
        /usr/bin/certbot renew --quiet
        /usr/bin/certbot certificates
        # back things up again:
        mkdir -p /run/nginx/.letsencrypt
        chmod u=rwx,go= /run/nginx/.letsencrypt
        tar --create --gzip --file=/run/nginx/.letsencrypt/letsencrypt.tgz /etc/letsencrypt /var/lib/letsencrypt /etc/nginx/sites-available/default
        chmod u=rx,go= /run/nginx/.letsencrypt
        echo "[$APPNAME][$(date)] nginx will restart now to ensure SSL is enabled"
        killall /usr/sbin/nginx
    done
fi
