#!/command/with-contenv bash
#shellcheck shell=bash disable=SC2154,SC1091

source /scripts/common

"${s6wrap[@]}" echo "Initial setup -- installing BLOCKBOT service"

mv -f /root/blockstats /usr/local/bin >/dev/null 2>&1
mv -f /root/ipmap /usr/local/bin >/dev/null 2>&1

if [[ -n "$BLOCKBOT" ]] || { [[ -n "$BLOCKBOT_REMOTELIST" ]] && ! chk_disabled "$BLOCKBOT_REMOTELIST"; }; then
  # shellcheck disable=SC2001
  BLOCKLIST="$(sed 's/,/|/g' <<< "$BLOCKBOT")"
  if [[ -n "$BLOCKBOT_REMOTELIST" ]] && ! chk_disabled "$BLOCKBOT_REMOTELIST"; then
    if chk_enabled "$BLOCKBOT_REMOTELIST"; then
      remote_url="https://raw.githubusercontent.com/sdr-enthusiasts/docker-reversewebproxy/main/blockbot-ua-list"
    else
      remote_url="$BLOCKBOT_REMOTELIST"
    fi
    if BLOCKLIST="$BLOCKLIST,$(curl -ssL "$remote_url")" && [[ "${BLOCKLIST:0:1}" == "," ]]; then
      BLOCKLIST="${BLOCKLIST:1}"
    fi
    if [[ "${BLOCKLIST: -1}" == "," ]]; then BLOCKLIST="${BLOCKLIST::-1}"; fi
  fi

  BLOCKLIST="${BLOCKLIST// /}"

  "${s6wrap[@]}" echo "Blocking these bots: $BLOCKLIST"
  { printf "map \$http_user_agent \$limit_bots {\n"
    printf "       default 0;\n"
    printf "       ~*(%s) 1;\n" "${BLOCKLIST// /}"
    printf "}\n"
  } >/etc/nginx/blockbot.conf
else
  "${s6wrap[@]}" echo "Bot blocking disabled"
  cp -f /etc/nginx/blockbot.conf.org /etc/nginx/blockbot.conf
  exit 0
fi

# If there is a BLOCKBOT_RESPONSECODE, then substitute it.
# Default code if omitted is 403 (Forbidden). Other codes that may be useful:
# 402 (payment required, hehe), 404 (doesn't exist), 418 (I am a teapot - used to tell requesters to go away), 410 (Gone), 500 (Internal Server Error),
# 503 (service unavailable), etc - see https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

[[ -z "$BLOCKBOT_RESPONSECODE" ]] && BLOCKBOT_RESPONSECODE="403"

if [[ "$BLOCKBOT_RESPONSECODE" -lt 100 ]] || [[ "$BLOCKBOT_RESPONSECODE" -gt 999 ]]
then
  "${s6wrap[@]}" echo "Response code value for blocked bots \"$BLOCKBOT_RESPONSECODE\" is invalid. Defaulting to \"403\"."
  BLOCKBOT_RESPONSECODE="403"
else
  "${s6wrap[@]}" echo "Setting response code for blocked bots to $BLOCKBOT_RESPONSECODE."
fi
# shellcheck disable=SC2016
sed -i '/\s*if ($limit_bots = 1)/{$!{N;s/\(\s*if ($limit_bots = 1) {\s*\n\s*return \)[0-9]*\(.*\)/\1'"$BLOCKBOT_RESPONSECODE"'\2/;ty;P;D;:y}}' /etc/nginx/sites-available/default >/dev/null 2>&1
