#!/command/with-contenv bash
#shellcheck shell=bash

# shellcheck disable=SC1091
source /scripts/common
# shellcheck disable=SC2154
"${s6wrap[@]}" echo "Final test of nginx before deployment"

# now test the nginx configuration
if ! /usr/sbin/nginx -g 'daemon off;' -t -q
then
    # nginx config problem. Complain and stop the container:
    "${s6wrap[@]}" echo "--------------------------------------------------"
    "${s6wrap[@]}" echo "|      STOP ! NGINX configuration problem        |"
    "${s6wrap[@]}" echo "| This is probably caused by a mal-formed        |"
    "${s6wrap[@]}" echo "| locations.conf file or by syntax errors in the |"
    "${s6wrap[@]}" echo "| definition of REVPROXY or REDIRECT in your     |"
    "${s6wrap[@]}" echo "| docker-compose.yml file. Go check and fix them!|"
    "${s6wrap[@]}" echo "--------------------------------------------------"

    if [[ -z "$DEBUG" ]]; then
        exit 1
    else
        exec sleep infinity
    fi
fi

exit 0
