#!/command/with-contenv bash
#shellcheck shell=bash disable=SC2154,SC1091

source /scripts/common

if ! chk_enabled "${VERBOSELOG}"; then
  "${s6wrap[@]}" echo "Logging to console is disabled. Set \"VERBOSELOG=on\" if you want to see the nginx access and error logs"
  sleep infinity
fi

# tail the log files to console:

{ "${s6wrap[@]}" tail -F /var/log/nginx/access.log; } &
accesspid="$!"

{ "${s6wrap[@]}" tail -F /var/log/nginx/error.log; } &
errorpid="$!"

# Wait until any of them exits for any reason
wait -n

# kill both processes before exiting, so the restart of the service is done cleanly
kill $accesspid >/dev/null 2>&1 || true
kill $errorpid >/dev/null 2>&1 || true
