#!/command/with-contenv bash
#shellcheck shell=bash disable=SC2154,SC1091

source /scripts/common

"${s6wrap[@]}" echo "Started as an s6 service"
"${s6wrap[@]}" echo "Starting the NGINX service..."

while true
do
    touch /tmp/nginx.up
    "${s6wrap[@]}" /usr/sbin/nginx -g 'daemon off;'
    rm -f /tmp/nginx.up
    "${s6wrap[@]}" echo "NGINX Service has exited."
    sleep 10
    "${s6wrap[@]}" echo "Restarting NGINX Service now..."
done
