#!/usr/bin/with-contenv bash
#shellcheck shell=bash

APPNAME="$(hostname)/blockbot-init"
echo "[$APPNAME][$(date)] Initial setup -- installing BLOCKBOT service"

if [[ -n "$BLOCKBOT" ]]
then
  BLOCKLIST="$(sed 's/,/|/g' <<< "$BLOCKBOT")"
  echo "[$APPNAME][$(date)] Blocking these bots: $BLOCKBOT"
  printf "map \$http_user_agent \$limit_bots {\n"           >/etc/nginx/blockbot.conf
  printf "       default 0;\n"                             >>/etc/nginx/blockbot.conf
  printf "       ~*(%s) 1;\n" "${BLOCKLIST// /}"           >>/etc/nginx/blockbot.conf
  printf "}\n"                                             >>/etc/nginx/blockbot.conf
  #echo "---------------"
  #cat /etc/nginx/blockbot.conf
  #echo "---------------"
else
  echo "[$APPNAME][$(date)] Bot blocking disabled"
  cp -f /etc/nginx/blockbot.conf.org /etc/nginx/blockbot.conf
fi
