#!/usr/bin/with-contenv bash
#shellcheck shell=bash

APPNAME="$(hostname)/reverse-proxy"

echo "[$APPNAME][$(date)] Started as an s6 service"
echo "[$APPNAME][$(date)] Starting the NGINX service..."

while true
do
    touch /tmp/nginx.up
    /usr/sbin/nginx -g 'daemon off;'
    rm -f /tmp/nginx.up
    echo "[$APPNAME][$(date)] NGINX Service has exited."
    sleep 10
    echo "[$APPNAME][$(date)] Restarting NGINX Service now..."
done
